import Head from "next/head";
import Link from "next/link";
import { Button, NavList } from "@primer/react";
import { BaseStyles, Box, Heading } from "@primer/react";
import { useRouter } from "next/router";
import { useState } from "react";

export default function Home() {
  const [alwaysOpen, setAlwaysOpen] = useState(false);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <BaseStyles>
          <Heading>Hi there</Heading>
          <Button onClick={() => setAlwaysOpen((p) => !p)}>
            {alwaysOpen ? "Close" : "Open"}
          </Button>
          <NList alwaysOpen={alwaysOpen} />
        </BaseStyles>
      </main>
    </>
  );
}

function NList({ alwaysOpen }: { alwaysOpen?: boolean }) {
  const { asPath } = useRouter();

  return (
    <NavList>
      <NavList.Item
        href="/"
        as={Link}
        aria-current={asPath === "/" ? "page" : undefined}
      >
        Home
      </NavList.Item>
      <NavList.Item
        href="/about"
        as={Link}
        aria-current={asPath === "/about" ? "page" : undefined}
        defaultOpen={alwaysOpen}
      >
        About
        <NavList.SubNav>
          <NavList.Item
            href="/about/things"
            aria-current={asPath === "/about/things" ? "page" : undefined}
            as={Link}
          >
            Things
          </NavList.Item>
          <NavList.Item
            href="/about/general"
            aria-current={asPath === "/about/general" ? "page" : undefined}
            as={Link}
            defaultOpen={alwaysOpen}
          >
            General
            <NavList.SubNav>
              <NavList.Item
                href="/about/general/one"
                aria-current={
                  asPath === "/about/general/one" ? "page" : undefined
                }
                as={Link}
              >
                General 1
              </NavList.Item>
              <NavList.Item
                href="/about/general/two"
                aria-current={
                  asPath === "/about/general/two" ? "page" : undefined
                }
                as={Link}
              >
                General 2
              </NavList.Item>
            </NavList.SubNav>
          </NavList.Item>
        </NavList.SubNav>
      </NavList.Item>
      <NavList.Item
        href="/contact"
        aria-current={asPath === "/contact" ? "page" : undefined}
        as={Link}
      >
        Contact
      </NavList.Item>
    </NavList>
  );
}
